use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Profile {
    pub id: String,
    pub name: String,
    pub hostname: String,
    #[serde(default)]
    pub addresses: Vec<String>,
    pub username: String,
    pub password: String,
    #[serde(default)]
    pub custom_sni: String,
    #[serde(default = "default_true")]
    pub has_ipv6: bool,
    #[serde(default = "default_protocol")]
    pub upstream_protocol: String,
    #[serde(default)]
    pub anti_dpi: bool,
    #[serde(default = "default_dns")]
    pub dns_upstreams: Vec<String>,
    #[serde(default = "default_vpn_mode")]
    pub vpn_mode: String,
    #[serde(default = "default_true")]
    pub killswitch_enabled: bool,
    #[serde(default = "default_true")]
    pub post_quantum_group_enabled: bool,
    #[serde(default)]
    pub exclusions: Vec<String>,
    #[serde(default)]
    pub skip_verification: bool,
    /// User-edited raw TOML overrides everything else when present.
    #[serde(default)]
    pub raw_toml: Option<String>,
}

fn default_true() -> bool {
    true
}
fn default_protocol() -> String {
    "http2".into()
}
fn default_dns() -> Vec<String> {
    vec!["1.1.1.1".into(), "tls://8.8.8.8".into()]
}
fn default_vpn_mode() -> String {
    "general".into()
}

impl Profile {
    pub fn new_blank(name: &str) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            name: name.to_string(),
            hostname: String::new(),
            addresses: vec![],
            username: String::new(),
            password: String::new(),
            custom_sni: String::new(),
            has_ipv6: true,
            upstream_protocol: "http2".into(),
            anti_dpi: false,
            dns_upstreams: default_dns(),
            vpn_mode: "general".into(),
            killswitch_enabled: true,
            post_quantum_group_enabled: true,
            exclusions: vec![],
            skip_verification: false,
            raw_toml: None,
        }
    }

    /// Render this profile as a full `trusttunnel_client.toml` body.
    /// If `raw_toml` is set, it wins (advanced users edited it directly).
    pub fn to_client_toml(&self) -> String {
        if let Some(raw) = &self.raw_toml {
            if !raw.trim().is_empty() {
                return raw.clone();
            }
        }
        let addrs = if self.addresses.is_empty() {
            vec![format!("{}:443", self.hostname)]
        } else {
            self.addresses.clone()
        };
        let exclusions_block = if self.exclusions.is_empty() {
            "exclusions = []".to_string()
        } else {
            let items: Vec<String> = self
                .exclusions
                .iter()
                .map(|e| format!("    \"{}\"", e.replace('"', "\\\"")))
                .collect();
            format!("exclusions = [\n{}\n]", items.join(",\n"))
        };
        let dns: Vec<String> = self
            .dns_upstreams
            .iter()
            .map(|d| format!("\"{}\"", d.replace('"', "\\\"")))
            .collect();
        let addrs_str: Vec<String> = addrs
            .iter()
            .map(|a| format!("\"{}\"", a.replace('"', "\\\"")))
            .collect();

        format!(
            r#"# Generated by TrustTunnel GUI for profile: {name}
loglevel = "info"
vpn_mode = "{vpn_mode}"
killswitch_enabled = {ks}
killswitch_allow_ports = []
post_quantum_group_enabled = {pq}

{exclusions}

[endpoint]
hostname = "{hostname}"
addresses = [{addrs}]
custom_sni = "{sni}"
has_ipv6 = {ipv6}
username = "{user}"
password = "{pass}"
client_random = ""
skip_verification = {skip}
certificate = ""
upstream_protocol = "{proto}"
anti_dpi = {anti_dpi}

dns_upstreams = [{dns}]

[listener]

[listener.tun]
bound_if = ""
included_routes = ["0.0.0.0/0", "2000::/3"]
excluded_routes = ["0.0.0.0/8", "10.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.168.0.0/16", "224.0.0.0/3"]
mtu_size = 1280
change_system_dns = true
"#,
            name = self.name.replace('"', "\\\""),
            vpn_mode = self.vpn_mode,
            ks = self.killswitch_enabled,
            pq = self.post_quantum_group_enabled,
            exclusions = exclusions_block,
            hostname = self.hostname,
            addrs = addrs_str.join(", "),
            sni = self.custom_sni,
            ipv6 = self.has_ipv6,
            user = self.username.replace('"', "\\\""),
            pass = self.password.replace('"', "\\\""),
            skip = self.skip_verification,
            proto = self.upstream_protocol,
            anti_dpi = self.anti_dpi,
            dns = dns.join(", "),
        )
    }

    /// Parse an existing `trusttunnel_client.toml` (full config) or a snippet
    /// like `conf.toml` (only endpoint fields at the top level) into a Profile.
    pub fn from_toml_str(toml_text: &str, fallback_name: &str) -> Result<Self> {
        let value: toml::Value = toml::from_str(toml_text).with_context(|| "TOML parse failed")?;

        let get_str = |table: &toml::Value, key: &str| -> Option<String> {
            table.get(key).and_then(|v| v.as_str()).map(String::from)
        };
        let get_bool = |table: &toml::Value, key: &str| -> Option<bool> {
            table.get(key).and_then(|v| v.as_bool())
        };
        let get_str_array = |table: &toml::Value, key: &str| -> Vec<String> {
            table
                .get(key)
                .and_then(|v| v.as_array())
                .map(|arr| {
                    arr.iter()
                        .filter_map(|x| x.as_str().map(String::from))
                        .collect()
                })
                .unwrap_or_default()
        };

        let endpoint = value
            .get("endpoint")
            .cloned()
            .unwrap_or_else(|| value.clone());

        let name = get_str(&value, "name")
            .or_else(|| get_str(&endpoint, "name"))
            .unwrap_or_else(|| fallback_name.to_string());

        let hostname = get_str(&endpoint, "hostname").unwrap_or_default();
        let addresses = get_str_array(&endpoint, "addresses");
        let username = get_str(&endpoint, "username").unwrap_or_default();
        let password = get_str(&endpoint, "password").unwrap_or_default();
        let custom_sni = get_str(&endpoint, "custom_sni").unwrap_or_default();
        let has_ipv6 = get_bool(&endpoint, "has_ipv6").unwrap_or(true);
        let upstream_protocol =
            get_str(&endpoint, "upstream_protocol").unwrap_or_else(|| "http2".into());
        let anti_dpi = get_bool(&endpoint, "anti_dpi").unwrap_or(false);
        let skip_verification = get_bool(&endpoint, "skip_verification").unwrap_or(false);

        let mut dns_upstreams = get_str_array(&endpoint, "dns_upstreams");
        if dns_upstreams.is_empty() {
            dns_upstreams = get_str_array(&value, "dns_upstreams");
        }
        if dns_upstreams.is_empty() {
            dns_upstreams = default_dns();
        }

        let vpn_mode = get_str(&value, "vpn_mode").unwrap_or_else(|| "general".into());
        let killswitch_enabled = get_bool(&value, "killswitch_enabled").unwrap_or(true);
        let post_quantum_group_enabled =
            get_bool(&value, "post_quantum_group_enabled").unwrap_or(true);
        let exclusions = get_str_array(&value, "exclusions");

        Ok(Profile {
            id: Uuid::new_v4().to_string(),
            name,
            hostname,
            addresses,
            username,
            password,
            custom_sni,
            has_ipv6,
            upstream_protocol,
            anti_dpi,
            dns_upstreams,
            vpn_mode,
            killswitch_enabled,
            post_quantum_group_enabled,
            exclusions,
            skip_verification,
            raw_toml: None,
        })
    }
}

#[derive(Debug, Default, Serialize, Deserialize)]
struct ProfileIndex {
    order: Vec<String>,
    active: Option<String>,
}

pub struct ProfileStore {
    root: PathBuf,
    inner: Mutex<ProfileStoreInner>,
}

#[derive(Default)]
struct ProfileStoreInner {
    profiles: Vec<Profile>,
    active: Option<String>,
}

impl ProfileStore {
    pub fn open(root: PathBuf) -> Result<Self> {
        fs::create_dir_all(&root)
            .with_context(|| format!("create profile dir {}", root.display()))?;
        let store = Self {
            root,
            inner: Mutex::new(ProfileStoreInner::default()),
        };
        store.reload()?;
        Ok(store)
    }

    fn index_path(&self) -> PathBuf {
        self.root.join("index.json")
    }

    fn profile_path(&self, id: &str) -> PathBuf {
        self.root.join(format!("{}.profile.json", id))
    }

    pub fn reload(&self) -> Result<()> {
        let mut profiles: Vec<Profile> = Vec::new();
        let mut order: Vec<String> = Vec::new();
        let mut active: Option<String> = None;

        let idx_path = self.index_path();
        if idx_path.exists() {
            let txt = fs::read_to_string(&idx_path).unwrap_or_default();
            if let Ok(idx) = serde_json::from_str::<ProfileIndex>(&txt) {
                order = idx.order;
                active = idx.active;
            }
        }

        if let Ok(entries) = fs::read_dir(&self.root) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().and_then(|s| s.to_str()) == Some("json")
                    && path
                        .file_name()
                        .and_then(|s| s.to_str())
                        .unwrap_or("")
                        .ends_with(".profile.json")
                {
                    if let Ok(txt) = fs::read_to_string(&path) {
                        if let Ok(p) = serde_json::from_str::<Profile>(&txt) {
                            profiles.push(p);
                        }
                    }
                }
            }
        }

        // sort by index order
        profiles.sort_by_key(|p| order.iter().position(|x| x == &p.id).unwrap_or(usize::MAX));

        let mut inner = self.inner.lock().unwrap();
        inner.profiles = profiles;
        inner.active = active;
        Ok(())
    }

    fn persist_index(&self, inner: &ProfileStoreInner) -> Result<()> {
        let idx = ProfileIndex {
            order: inner.profiles.iter().map(|p| p.id.clone()).collect(),
            active: inner.active.clone(),
        };
        let txt = serde_json::to_string_pretty(&idx)?;
        fs::write(self.index_path(), txt)?;
        Ok(())
    }

    fn persist_profile(&self, profile: &Profile) -> Result<()> {
        let txt = serde_json::to_string_pretty(profile)?;
        fs::write(self.profile_path(&profile.id), txt)?;
        Ok(())
    }

    pub fn list(&self) -> Vec<Profile> {
        self.inner.lock().unwrap().profiles.clone()
    }

    pub fn active_id(&self) -> Option<String> {
        self.inner.lock().unwrap().active.clone()
    }

    pub fn set_active(&self, id: Option<String>) -> Result<()> {
        let mut inner = self.inner.lock().unwrap();
        inner.active = id;
        self.persist_index(&inner)
    }

    pub fn get(&self, id: &str) -> Option<Profile> {
        self.inner
            .lock()
            .unwrap()
            .profiles
            .iter()
            .find(|p| p.id == id)
            .cloned()
    }

    pub fn upsert(&self, profile: Profile) -> Result<Profile> {
        let mut inner = self.inner.lock().unwrap();
        if let Some(existing) = inner.profiles.iter_mut().find(|p| p.id == profile.id) {
            *existing = profile.clone();
        } else {
            inner.profiles.push(profile.clone());
        }
        self.persist_profile(&profile)?;
        self.persist_index(&inner)?;
        Ok(profile)
    }

    pub fn delete(&self, id: &str) -> Result<()> {
        let mut inner = self.inner.lock().unwrap();
        inner.profiles.retain(|p| p.id != id);
        if inner.active.as_deref() == Some(id) {
            inner.active = None;
        }
        let path = self.profile_path(id);
        if path.exists() {
            let _ = fs::remove_file(&path);
        }
        self.persist_index(&inner)?;
        Ok(())
    }

    pub fn import_toml_text(&self, text: &str, fallback_name: &str) -> Result<Profile> {
        let profile = Profile::from_toml_str(text, fallback_name)?;
        self.upsert(profile)
    }

    pub fn import_toml_file(&self, path: &Path) -> Result<Profile> {
        let text = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        let fallback = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("Imported")
            .to_string();
        self.import_toml_text(&text, &fallback)
    }
}
